### ISSUE TITLE
Symfony Forms Unable to generate a URL for the named route "/yatzy/roll" as such route does not exist

### ISSUE THREAD

**Issue by fahlstrm** [dbwebb-se/mvc#28]
Har försökt skapa formulär enligt Symfonys dokumentation, men lyckas inte.
Försöker därför behålla html-formuläret och ange en action för att kunna styra vilken metod i controllern som anropas:
`<form action="{{ path('/yatzy/roll') }}" method="post">`
Men får felmeddelande _Unable to generate a URL for the named route "/yatzy/roll" as such route does not exist_

- Routen finns, dubbelkollat via php bin/console debug:router
- Skriver jag ut nuvarande path är den /yatzy

Går det ange en action och korrekt route via twig? 
Vilken path() bör jag isåfall ange?

**Comment by fahlstrm** [comment]
Testar följande där jag angivit fel path, istället för _path('/yatzy/roll')_ borde _path('yatzy_roll')_
```
yatzy_roll:
    path: /yatzy/roll
    controller: App\Controller\YatzyController::roll
    methods: POST

```
