### ISSUE TITLE
Code coverage: Scrutinizer vs. php-code-coverage

### ISSUE THREAD

**Issue by radonhus** [dbwebb-se/mvc#39]
![php-code-coverage](https://user-images.githubusercontent.com/71336413/117711210-3c21dc80-b1d3-11eb-99f0-e1f4eafc4aa2.png)
![scrut](https://user-images.githubusercontent.com/71336413/117711217-3cba7300-b1d3-11eb-8a0b-f9a0e805a2b6.png)

Mina enhetstester för controller-klasserna verkar inte riktigt accepteras under code coverage på Scrutinizer. Konstigt nog har jag fått A-betyg under en annan flik (se nedan). Även där visas att 0 % av metoderna testats. 

Vad skulle kunna vara fel? Nedan finns även min .scrutinizer.yml och .phpunit.xml.

https://scrutinizer-ci.com/g/radonhus/bth-mvc-framework/

![scrut-ratings](https://user-images.githubusercontent.com/71336413/117711492-9de24680-b1d3-11eb-8e22-df8e8525adbb.png)

```
<?xml version="1.0" encoding="UTF-8"?>
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" bootstrap="tests/config.php" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd">
  <coverage processUncoveredFiles="true">
    <include>
        <directory suffix=".php">app/Http/Controllers</directory>
        <directory suffix=".php">app/Models/Book</directory>
        <directory suffix=".php">app/Models/Game21</directory>
        <directory suffix=".php">app/Models/Yatzy</directory>
        <file>routes/web.php</file>
    </include>
    <exclude>
        <file>./app/Http/Controllers/Controller.php</file>
    </exclude>
    <report>
        <clover outputFile="build/coverage.clover"/>
        <html outputDirectory="build/coverage" lowUpperBound="35" highLowerBound="70"/>
    </report>
  </coverage>
  <testsuites>
    <testsuite name="all">
      <directory>tests/Feature</directory>
      <directory>tests/Unit/Game21</directory>
      <directory>tests/Unit/Yatzy</directory>
    </testsuite>
  </testsuites>
  <logging/>
  <php>
    <env name="APP_ENV" value="testing" force="true"/>
  </php>
</phpunit>
```

```
imports:
    - php

filter:
    paths: ["app/Models/*", "app/Http/Controllers/*", "routes/web.php"]
    excluded_paths: [vendor/*, build/*, app/Models/User.php]

build:
    nodes:
        my-tests:
            environment:
                php:
                    version: 7.4
    tests:
        override:
            -
                command: "make phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"
```
